# Generated by Django 5.0.1 on 2024-03-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staticdynamicapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Great",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name1", models.CharField(max_length=250)),
                ("img1", models.ImageField(upload_to="picsart")),
                ("des1", models.TextField()),
            ],
        ),
    ]
