# Generated by Django 5.0.1 on 2024-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staticdynamicapp", "0002_great"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name2", models.CharField(max_length=250)),
                ("img2", models.ImageField(upload_to="picsart")),
                ("des2", models.TextField()),
            ],
        ),
    ]
