# Generated by Django 5.0.1 on 2024-03-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staticdynamicapp", "0003_goose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goose",
            name="img2",
            field=models.ImageField(upload_to="picsarss"),
        ),
    ]
