# Generated by Django 5.0.1 on 2024-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staticdynamicapp", "0005_goofy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name4", models.CharField(max_length=250)),
                ("img4", models.ImageField(upload_to="picsard")),
                ("des4", models.TextField()),
            ],
        ),
    ]
