# Generated by Django 5.0.1 on 2024-03-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staticdynamicapp", "0006_gog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gog",
            name="img4",
            field=models.ImageField(upload_to="picsardds"),
        ),
    ]
